[package]
name = "compress"
version = "0.2.0"
edition = "2021"

[dependencies]
zstd-sys-rs = "1.5.10"
walkdir = "2.5.0"
blake3 = "1.8.2"
anyhow = "1.0.98"
crossbeam-channel = "0.5.15"
arrow = "55.2.0"
znippy-common = { path = "../znippy-common" }
log = "0.4.27"

